version: '3.8'

services:
  db:
    image: postgres:15  # Use the latest stable PostgreSQL version
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: trade_db_admin
      POSTGRES_PASSWORD: TRADES123!
      POSTGRES_DB: trades_db
    ports:
      - "5432:5432"  # Map the local machine's port to the Docker container port
    volumes:
      - pgdata:/var/lib/postgresql/data     # Persistent storage for database
      - ./db_init:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
    driver: local